name: ODM

on:
  push:
    branches: [ "ak/automate-build" ]
  pull_request:
    branches: [ "ak/automate-build" ]

jobs:

  build:

    runs-on: windows-2022

    env:
      Solution_Name: odm.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install net40
      run: |
       .\libs\dotnet40\dotNetFx40_Full_setup.exe /q /norestart
       choco install netfx-4.0.1-devpack netfx-4.0.3-devpack -y
       type C:\Users\runneradmin\AppData\Local\Temp\chocolatey\netfx-4.0.3-devpack.log
      continue-on-error: true

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4      

    - name: build application
      run: devenv ${{ env.Solution_Name }} /Build "Release|x64" /Project odm.ui.app
    
    - name: collect artifacts
      run: package.bat
      shell: cmd
    
    - name: upload artifacts 
      uses: actions/upload-artifact@v4
      with:
        name: odm-build-zip
        path: build/

    - name: DisableOutOfProcBuild
      working-directory: ${{env.DevEnvDir}}\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild
      run: .\DisableOutOfProcBuild.exe
      continue-on-error: true

    - name: build installer
      run: devenv ${{ env.Solution_Name }} /Build "Release|x64" /Project odm.setup
      shell: cmd

    - name: upload installer 
      uses: actions/upload-artifact@v4
      with:
          name: odm-installer
          path: odm.setup/Release/odm.setup.msi
  